
.common_build_job:
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ${GASPI_BUILD_DIR}
  script:
    - echo GASPI_BUILD_TYPE=${GASPI_BUILD_TYPE}
    - echo GASPI_USE_IB=${GASPI_USE_IB}
    - echo GASPI_BARRIER_TIMEOUT=${GASPI_BARRIER_TIMEOUT}
    - echo GASPI_TEST_MACHINEFILE=${GASPI_TEST_MACHINEFILE}
    - rm -rf ${GASPI_INSTALL_DIR}
    - rm -rf ${GASPI_BUILD_DIR} && mkdir ${GASPI_BUILD_DIR}
    - cd ${GASPI_BUILD_DIR}
    - cmake -DTEST_MACHINEFILE=${GASPI_TEST_MACHINEFILE} -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=${GASPI_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${GASPI_INSTALL_DIR} -DENABLE_TESTS=ON ${CI_PROJECT_DIR}
    - make -j$(nproc)

.common_after_script:
  after_script:
    - sh ${CI_PROJECT_DIR}/cmake/cleanup.sh 

.release_job:
  variables:
    GASPI_BUILD_TYPE: Release

.debug_job:
  variables:
    GASPI_BUILD_TYPE: Debug

.eth_job:
  variables:
    GASPI_GPI2_MODULE: ${GPI2_MODULE_ETH}

.ib_job:
  variables:
    GASPI_GPI2_MODULE: ${GPI2_MODULE_IB}